# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BraveWidgetsExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BraveWidgetsExtension

end

target 'BrowserIntents' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BrowserIntents

end

target 'Client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TensorFlowLiteSwift'
  # Pods for Client

end

target 'ShareExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShareExtension

end
